/*
 *
 * This file contains PROGMEM constants for custom selection of musical instruments
 * available in the ATEMP Pro.DX synthesizer.
 *
 */

#ifndef _PRODX_H
#define _PRODX_H

// groups of instruments
const char dxGroupName0[]  PROGMEM  = "Pianos";
const char dxGroupName1[]  PROGMEM  = "El Pianos";
const char dxGroupName2[]  PROGMEM  = "Chrom Perc";
const char dxGroupName3[]  PROGMEM  = "Organs";
const char dxGroupName4[]  PROGMEM  = "Guitars";
const char dxGroupName5[]  PROGMEM  = "El Guitars";
const char dxGroupName6[]  PROGMEM  = "Bass";
const char dxGroupName7[]  PROGMEM  = "Synth Bass";
const char dxGroupName8[]  PROGMEM  = "Strings";
const char dxGroupName9[]  PROGMEM  = "Ensemble";
const char dxGroupName10[] PROGMEM  = "Brass";
const char dxGroupName11[] PROGMEM  = "Reed";
const char dxGroupName12[] PROGMEM  = "Winds";
const char dxGroupName13[] PROGMEM  = "Leads";
const char dxGroupName14[] PROGMEM  = "Pads";
const char dxGroupName15[] PROGMEM  = "EFX";
const char dxGroupName16[] PROGMEM  = "Ethnic";
const char dxGroupName17[] PROGMEM  = "Drum Perc";
const char dxGroupName18[] PROGMEM  = "Sounds";
//
#define dxNumberOfGroups    19
//
const char * const  dxGroupName[dxNumberOfGroups] PROGMEM = {
    dxGroupName0, dxGroupName1, dxGroupName2, dxGroupName3, dxGroupName4, dxGroupName5, dxGroupName6, dxGroupName7, 
    dxGroupName8, dxGroupName9, dxGroupName10, dxGroupName11, dxGroupName12, dxGroupName13, dxGroupName14, dxGroupName15, 
    dxGroupName16, dxGroupName17, dxGroupName18
};
// Last Program ID for each group
const uint8_t dxGroupMap[dxNumberOfGroups] PROGMEM = {
    3, // Pianos
    5, // El Pianos
    15, // Chrom Perc
    23, // Organs
    25, // Guitars
    31, // El Guitars
    37, // Bass
    39, // Synth Bass
    47, // Strings
    55, // Ensemble
    63, // Brass
    71, // Reed
    79, // Winds
    87, // Leads
    95, // Pads
    103, // EFX
    111, // Ethnic
    119, // Drum Perc
    127  // Sounds
};
// All Instrument names
const char dxInstrumentNames[] PROGMEM    =
    "Concert Grand\0"
    "Classic Grand\0"
    "Pop Grand\0"
    "Rock Grand\0"
    "Rock B Grand\0"
    "CP-Piano 80\0"
    "Honkytonk\0"
    "Old Piano\0"
    "Rhodex MKII-S\0"
    "Suitsace MK I\0"
    "70s Vintage\0"
    "Rhodex MB\0"
    "Suitsace MK II\0"
    "Old MK II\0"
    "Bell MK II\0"
    "Wwurluzzer\0"
    "Real DX\0"
    "Sort  DX\0"
    "DX Piano\0"
    "Detuned EP 2\0"
    "Cembalo\0"
    "French Harpsi\0"
    "Coup. Harpsi\0"
    "Clavinette\0"
    "Clav D 6\0"
    "Celeste\0"
    "Glockenspiel\0"
    "Musicbox\0"
    "Vibes\0"
    "Harimba\0"
    "Barafon\0"
    "Xylophone\0"
    "Tubular Bell\0"
    "Church Bell\0"
    "Carillion\0"
    "Dulcimar\0"
    "Santur 2\0"
    "Vintage B Organ\0"
    "Organ 101\0"
    "Organ 1\0"
    "Organ Slow B\0"
    "Organ 109\0"
    "60's Organ 1\0"
    "Even Bar\0"
    "Organ Bass\0"
    "Jazz Perc Organ\0"
    "Organ 201\0"
    "Organ 2\0"
    "Theater Organ\0"
    "Detuned Organ-2\0"
    "Percuss. Organ\0"
    "Rock Organ\0"
    "Rotary  Organ\0"
    "Rotary  Organ S\0"
    "Rotary  Organ F\0"
    "Church Tutti\0"
    "Church Organ 1\0"
    "Principal 8\0"
    "Principal 8+4\0"
    "Small Pipe 8\0"
    "Small Pipe 16+8\0"
    "Church Organ 2\0"
    "Reed Organ\0"
    "Musette\0"
    "German Accord.\0"
    "Aplin Accordeon\0"
    "German Lucia\0"
    "Accordion It.\0"
    "Bluesharp\0"
    "Harmonica\0"
    "Bandoneon\0"
    "60-Classic-Nyl.\0"
    "Nylon G. Pic\0"
    "Classic 1P\0"
    "Ukulele\0"
    "Classic S\0"
    "Velo Harmonics\0"
    "Spain Guitar\0"
    "Nylon Finger\0"
    "Western TKM\0"
    "Western GT\0"
    "12 String MB\0"
    "Mandolin\0"
    "Mando-tremolo\0"
    "Mando & Tremolo\0"
    "Steel Guitar OV\0"
    "Jazzy Blues\0"
    "ES Jazz H\0"
    "Jazz Guitar\0"
    "Hawaian Guitar\0"
    "Real Strato\0"
    "Ultra Clean\0"
    "Clean LP Soft\0"
    "Chorus Clean\0"
    "Mute Git\0"
    "Overdrive RE\0"
    "Tele Distorsion\0"
    "LP-Distorsion\0"
    "Feedback Guitar\0"
    "G. Harmonics\0"
    "G. Feedback\0"
    "Upright Bass\0"
    "Double Bass\0"
    "Dbl Bass & Ride\0"
    "Jazz Bass\0"
    "FingerSlap Bass\0"
    "Music M-Bridge\0"
    "Rock Bass\0"
    "Jazz Bass 2\0"
    "Mute Bass\0"
    "Fretless\0"
    "Slap Bass 59\0"
    "Slap Bass 2-2\0"
    "Synth Bass  1\0"
    "Synth Bass  3\0"
    "TB303 Bass\0"
    "Tekhno Bass\0"
    "Tekhno  Bass 2\0"
    "Seq 303 Overdr\0"
    "Seq 303\0"
    "Reso SH Bass\0"
    "Synth Bass 3-2\0"
    "Wedge Bass\0"
    "Synth Bass 2-2\0"
    "Modular  Bass 2\0"
    "Seq Bass MG\0"
    "Analog Bass\0"
    "Synth Bass 201\0"
    "Synth  Bass 1-2\0"
    "Synth-Bass 4\0"
    "Rubber Bass\0"
    "SH101 Bass 2\0"
    "Smooth Bass\0"
    "Violin 1\0"
    "Violin\0"
    "Viola\0"
    "Classic Cello\0"
    "Contrabass D\0"
    "Tremolo str\0"
    "Pizzicato\0"
    "Pizz String D\0"
    "Harp\0"
    "Pakuten\0"
    "Timpani D\0"
    "Real Strings\0"
    "Orch Strings\0"
    "Class. String\0"
    "Chamber Ens\0"
    "Slow String Ens\0"
    "Soft Strings\0"
    "JX Strings\0"
    "OB_X Strings 2\0"
    "Synth Strings 3\0"
    "Juno Strings\0"
    "Synth Strings 2\0"
    "Classic Chor\0"
    "Ahh Chor\0"
    "Chor Aahs\0"
    "Uhh Chor\0"
    "Mixed Choir\0"
    "Male  Ahh Synth\0"
    "Synth Voices\0"
    "Orchastra Hit\0"
    "Impact Hit\0"
    "Philly  Hit\0"
    "Trompete\0"
    "Soft Trumpet\0"
    "Fluegelhorn\0"
    "Trombone\0"
    "Tuba\0"
    "Bariton-1\0"
    "Bariton+Bass\0"
    "Mute Trumpet\0"
    "Muted Trumpet-2\0"
    "French Horns\0"
    "Super Brass\0"
    "Super Brass Sec\0"
    "Fat Brass Sect\0"
    "SuperBrass Oct\0"
    "Matrix Brass 2\0"
    "Brass Fall\0"
    "Matrix Brass 1\0"
    "DW-Brass 8\0"
    "OB-X-Synth\0"
    "Synth Brass 1\0"
    "Super Saw\0"
    "OB-X Brass\0"
    "Tekno Synth\0"
    "Synth Brass 61\0"
    "Synth Brass 2\0"
    "Synth Brass  4\0"
    "Soprano\0"
    "Stonys L Alto\0"
    "Jazzy Sax\0"
    "Alto Sax\0"
    "Live Sax MS\0"
    "Tenor Sax\0"
    "Stony Soft Sax\0"
    "Rock Sax RTC\0"
    "Bariton  Sax\0"
    "Oboe\0"
    "English Horn-2\0"
    "Bassoon-2\0"
    "Clarinet\0"
    "Folk  Clarinet\0"
    "Piccolo\0"
    "Overfloete\0"
    "Dynamic Flute\0"
    "Recorder\0"
    "Thinwistle\0"
    "Pan Flute\0"
    "Bottle Blow\0"
    "Shakuhachi\0"
    "Whistle\0"
    "Ocarina\0"
    "Square Lead\0"
    "Square Wave\0"
    "Sine Wave\0"
    "Mini-Lead1\0"
    "Saw Wave\0"
    "Saw Lead\0"
    "Synth Calliope\0"
    "Chiffer Lead\0"
    "Charang\0"
    "Solo Synth  Vox\0"
    "5th Saw Wave\0"
    "Bass & Lead\0"
    "Fantasy D\0"
    "Staccato Sky\0"
    "Staccato Himmel\0"
    "Warm Pad 1\0"
    "Analog Strings\0"
    "Warm Pad\0"
    "Rotary String\0"
    "OB-X-Strings  1\0"
    "Saw Wave\0"
    "Palisynth Pad\0"
    "Voxair\0"
    "Space Voice Pad\0"
    "Bowed Glass Pad\0"
    "Metal Pad\0"
    "Halo Pad\0"
    "Sweep Pad\0"
    "Ice Rain\0"
    "Sondtrack\0"
    "Crystal\0"
    "Atmosphere\0"
    "Brightness\0"
    "Goblin\0"
    "Echo Drops\0"
    "Echo Pan\0"
    "Star Theme\0"
    "Sitar\0"
    "Banjo\0"
    "Shamisen\0"
    "Koto\0"
    "Zither\0"
    "Kalimba\0"
    "Bagpipe\0"
    "Fiddle\0"
    "Shanai\0"
    "Tinkle Bell\0"
    "Agogo\0"
    "Steel Drums\0"
    "Manual Drumset\0"
    "Woodblock\0"
    "Castanets\0"
    "Taiko\0"
    "Concert  Bass D\0"
"90\0"//    "Melodic Tom 1\0"
"91\0"//    "Melodic Tom 2\0"
"92\0"//    "Synth Drum\0"
"93\0"//    "808  Tom\0"
"94\0"//    "El  Percussion\0"
"95\0"//    "Reverse Cymbal\0"
"96\0"//    "G. Fret Noise\0"
"97\0"//    "G. Cut Noise\0"
"98\0"//    "String Slap\0"
"99\0"//    "Bass Slide\0"
".0\0"//    "Pick Scrape\0"
".1\0"//    "Breath  Noise\0"
".2\0"//    "Fluite Key Clk\0"
".3\0"//    "Bubble\0"
".4\0"//    "Seashore\0"
".5\0"//    "Rain\0"
".6\0"//    "Thunder\0"
".7\0"//    "Wind\0"
".8\0"//    "Stream\0"
".9\0"//    "Bird\0"
"-0\0"//    "Dog\0"
"-1\0"//    "Horse Gallop\0"
"-2\0"//    "Bird 2\0"
"-3\0"//    "Telephone 1\0"
"-4\0"//    "Telephone 2\0"
"-5\0"//    "Door Creaking\0"
"-6\0"//    "Door Closing\0"
"-7\0"//    "Scratch\0"
"-8\0"//    "Wind Chimes\0"
"-9\0"//    "Helicopter\0"
"00\0"//    "Car-Engine\0"
"01\0"//    "Car-Stop\0"
"02\0"//    "Car-Pass\0"
"03\0"//    "Car-Crash\0"
"04\0"//    "Siren\0"
"05\0"//    "Train\0"
"06\0"//    "Jet  Plane\0"
"07\0"//    "Starship\0"
"08\0"//    "Burst Noise\0"
"09\0"//    "Applause\0"
"10\0"//    "Laughing\0"
"11\0"//    "Screaming\0"
"12\0"//    "Punch\0"
"13\0" //    "Heart Beat\0"
"14\0" //    "Footsteps\0"
"15\0" //    "Gun Shot\0"
"16\0" //    "Machine  Gun\0"    TODO uncomment this back when we don't need to save memory
"17\0" //    "Laser Gun\0"
"18\0"; //    "Explosion\0";
//
#define dxNumberOfInstruments   318
//
#endif
